### ISSUE TITLE
Same origin policy

### ISSUE THREAD

**Issue by mavogel** [SimonFindling/ui-lab#13]
Set header for same origin policy to allow calls from everywhere.

**Comment by RayComBomber** [comment]
Which header do you mean? 
Did we decided to remove all ".../{tenantId}/..." from the URLs and place them in a extra Header-Filed "X-Tenant" or do we keep the TenantId in the URL?

**Comment by Junkern** [comment]
The project from the UI-groups is running under a different origin, than the server (e.g. `localhost:3000` for the UI-groups and the server under some IP). Making an XHR is not possible. Therefore, the server has to explicit enable the cross-origin exchange of information. We possible need all three headers:

```
Access-Control-Allow-Origin: * 
Access-Control-Allow-Credentials: true  
Access-Control-Expose-Headers: ##maybe X-Tenant?
```

For more information: <https://www.html5rocks.com/en/tutorials/cors/#toc-adding-cors-support-to-the-server>
