### ISSUE TITLE
Account Service

### ISSUE THREAD

**Issue by mavogel** [SimonFindling/ui-lab#7]
## 08.12.2016
- [x] Accounts can be created for prospects and customers 
- [x] Restructure the DB Layout for users
- [x] Rethink the JSON payloads 
- ~Evaluate mongodb as db~
- [x] Create schema from Entities via hibernate
- [x] Add MySQL docker container with automated SERVICE creation in db
- ~Evaluate MySQL schema updates~

## 15.12.2016
- [ ] `X-Tenant` header + db field
- [x] strip api gateway prefix
- ~~Add integration tests~~

## 22.12.2016
- [x] remove rest-jpa deps and fix JSON results. Will fix #11 
- [x] fix ports in rest doc. remove quick fix as well

**Comment by Junkern** [comment]
I found a solution for *remove rest-jpa deps and fix JSON results*
If you still need help with that, I could post a gist here.

**Comment by mavogel** [comment]
Could you post the gist here please. 
I'd rather prefer to map the result JSON correctly with the id, so you don't have to strip the data

**Comment by Junkern** [comment]
https://gist.github.com/Junkern/a813d71ce9291e11bd0ec720143eeffb

**Comment by mavogel** [comment]
I fixed it by introducing dtos and automated mapping, which we will probably need in other services.
